ex186a is

  f is
    say "perform exit:"
    exit 0
    say "** not reachable code **"

  my_exit : Exit_Handler is
    exit(code i32) void =>
      io.err.println "*** user defined exit handler diverting exit $code ***"
      exit.env.abort

  exit my_exit ()->
    f
    say "** not reachable code **"

  say "continue even though exit was called..."
